Repository MicrosoftDocs/OfficeDocs-SkypeForBusiness, pull requests merged in 2018-10, with the labels that each got.

#833 updated for readability
  Skype/SfbServer/deploy/deploy-clients/lrs-migration.md
Labels: Microsoft submitter

#835 added 4.0.27.0 release notes
  Skype/SfbServer/plan-your-deployment/clients-and-devices/srs2-release-note.md
Labels: Microsoft submitter

#761 Added resolution for issue where the CloudConnector module cannot be …
  Skype/SfbServer/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/troubleshoot-your-cloud-connector-deployment.md
Labels: Skype for Business Server

#694 update for Public team list not displaying
  Teams/Known-issues.md
Labels: Microsoft Teams

#839 Remove note about not being supported yet.
  Skype/SfbServer/plan-your-deployment/requirements-for-your-environment/server-requirements.md
Labels: Microsoft submitter

#827 Make Mobile Clients for Teams more clear
  Teams/get-clients.md
Labels: Microsoft Teams

#840 Update migration-interop-guidance-for-teams-with-skype.md
  Teams/migration-interop-guidance-for-teams-with-skype.md
Labels: Microsoft submitter

#841 Update requirements.md
  Skype/SfbServer/plan-your-deployment/clients-and-devices/requirements.md
Labels: Microsoft submitter

#851 typo + note
  Skype/SfbServer/deploy/deploy-clients/lrs-migration.md
Labels: Microsoft submitter

#853 updated link for smart
  Skype/SfbServer/deploy/deploy-clients/lrs-migration.md
Labels: Microsoft submitter

#855 Update meetings-clients.md
  Skype/SfbServer/plan-your-deployment/clients-and-devices/meetings-clients.md
Labels: Microsoft submitter

#860 Update migration-interop-guidance-for-teams-with-skype.md
  Teams/migration-interop-guidance-for-teams-with-skype.md
Labels: Microsoft submitter

#865 Update requirements.md
  Skype/SfbServer/plan-your-deployment/clients-and-devices/requirements.md
Labels: Microsoft submitter

#863 added link + grammar update
  Skype/SfbServer/deploy/deploy-clients/lrs-migration.md
Labels: Microsoft submitter

#880 updated link to License page
  Skype/SfbServer/room-systems/toc.md
Labels: Microsoft submitter

#883 added link
  Skype/SfbServer/deploy/deploy-clients/with-office-365.md
Labels: Microsoft submitter

#885 Adding known issue about EAF policy
  Teams/Known-issues.md
Labels: Microsoft submitter

#887 Update migration-interop-guidance-for-teams-with-skype.md
  Teams/migration-interop-guidance-for-teams-with-skype.md
Labels: Microsoft submitter

#892 Updated Help experience article
  Teams/help.md
Labels: Microsoft submitter

#893 Addressing user feedback
  Teams/Known-issues.md
Labels: Microsoft submitter

#882 updated link
  Skype/SfbServer/room-systems/toc.md
Labels: Microsoft submitter

#881 updated min win build number
  Skype/SfbOnline/skype-for-business-and-microsoft-teams-add-on-licensing/license-options-based-on-your-plan/skype-room-systems-v2.md
Labels: Microsoft submitter

#894 Revert "Updated Help experience article"
  Teams/help.md
Labels: Microsoft submitter

#900 Update users-can-make-outbound-calls-to-these-countries-and-regions.md
  Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/users-can-make-outbound-calls-to-these-countries-and-regions.md
Labels: Microsoft submitter

#903 Updating known issues for Teams
  Teams/Known-issues.md
Labels: Microsoft submitter

#904 Update known Issues for Teams
  Teams/Known-issues.md
Labels: Microsoft submitter

#902 removed specific version of window reference
  Skype/SfbOnline/skype-for-business-and-microsoft-teams-add-on-licensing/license-options-based-on-your-plan/skype-room-systems-v2.md
Labels: Microsoft submitter

#907 Update definition of other activity
  Teams/teams-activity-reports.md
Labels: Microsoft submitter

#910 Tls updates
  Skype/SfbServer/deploy/deploy-clients/lrs-migration.md
Labels: Microsoft submitter

#911 4.0.31.0 release notes
  Skype/SfbServer/plan-your-deployment/clients-and-devices/srs2-release-note.md
Labels: Microsoft submitter

#912 Fixed typo
  Lync/LyncServer/lync-server-2013-moving-response-groups-to-a-new-pool.md
Labels: Microsoft submitter

#914 And Andrea Barr who is managing issues and prs.
  CODEOWNERS
Labels: Microsoft submitter

#921 `supportsFiles` no longer in developer preview
  Teams/app-permissions.md
Labels: Microsoft submitter

#923 Update to indicate that group management is available
  Teams/using-admin-roles.md
Labels: Microsoft submitter

#920 Need to clarify the NOTE about "CAP account's password will be chang…
  Skype/SfbOnline/what-is-phone-system-in-office-365/getting-phones-for-skype-for-business-online/setting-up-common-area-phones.md
Labels: Microsoft submitter

#913 Adding newly qualified SIP Trunking providers
  Skype/SfbPartnerCertification/certification/services-sip-trunking.md
Labels: Microsoft submitter

#931 Update Known-issues.md
  Teams/Known-issues.md
Labels: Microsoft submitter

#944 Add Exchange Server minimum requirement.
  Skype/SfbServer/plan-your-deployment/clients-and-devices/requirements.md
Labels: Microsoft submitter

#948 Update direct-routing-border-controllers.md
  Teams/direct-routing-border-controllers.md
Labels: Microsoft submitter

#955 Update direct-routing-border-controllers.md
  Teams/direct-routing-border-controllers.md
Labels: Microsoft submitter

#991 Adding Nikolay to ms.reviewer field for sign off for this doc.
  Teams/direct-routing-border-controllers.md
Labels: Microsoft submitter

#995 Update configure-azure-ad-connect.md
  Skype/SfBServer2019/hybrid/configure-azure-ad-connect.md
Labels: Microsoft submitter

#993 Updated license requirements
  Teams/cloud-recording.md
Labels: Microsoft submitter

#992 Update devices-Pc.md
  Skype/SfbPartnerCertification/certification/devices-pcs.md
Labels: Microsoft submitter

#996 Update move-users-from-on-premises-to-teams.md
  Skype/SfBServer2019/hybrid/move-users-from-on-premises-to-teams.md
Labels: Microsoft submitter

#998 Update availability-in-the-united-kingdom-u-k.md
  Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-kingdom-u-k.md
Labels: Microsoft submitter

#1002 added ms.reviewer
  Teams/create-an-org-wide-team.md
Labels: Microsoft submitter

#1004 Update plan-hybrid-connectivity.md
  Skype/SfBServer2019/hybrid/plan-hybrid-connectivity.md
Labels: Microsoft submitter
