Repository MicrosoftDocs/OfficeDocs-SkypeForBusiness, pull requests merged in 2018-09, with the labels that each got.

#728 Update teams-surface-hub.md
  Teams/teams-surface-hub.md
Labels: Microsoft submitter

#746 Update requirements.md
  Skype/SfbServer/plan-your-deployment/clients-and-devices/requirements.md
Labels: Microsoft submitter

#706 Update exchange-unified-messaging.md
  Skype/SfbServer/management-tools/planning-tool/exchange-unified-messaging.md
Labels: Microsoft submitter

#750 Added note stemming from confusion around browser/OS.
  Teams/includes/browser-support.md
Labels: Microsoft submitter

#751 Update direct-routing-sbc-multiple-tenants.md
  Teams/direct-routing-sbc-multiple-tenants.md
Labels: Microsoft submitter

#743 Update get-clients.md
  Teams/get-clients.md
Labels: Microsoft submitter

#727 Packet loss metrics in CQD are reported as ratios
  Teams/dimensions-and-measures-available-in-call-quality-dashboard.md
Labels: Microsoft submitter

#726 CQD date and time values are reported in UTC
  Teams/dimensions-and-measures-available-in-call-quality-dashboard.md
Labels: Microsoft submitter

#725 Wifi signal strength reported in CQD is in the range [0, 100]
  Teams/dimensions-and-measures-available-in-call-quality-dashboard.md
Labels: Microsoft submitter

#699 correct capitalization for Intune
  Teams/teams-surface-hub.md
Labels: Microsoft submitter

#759 Replace new video embed codes
  Teams/ITAdmin-readiness.md
Labels: Microsoft submitter

#768 Update migration-interop-guidance-for-teams-with-skype.md
  Teams/migration-interop-guidance-for-teams-with-skype.md
Labels: Microsoft submitter

#780 Starting with CU7 SQL Server 2016 SP1 is supported as per KB4100776
  Skype/SfbServer/plan-your-deployment/persistent-chat-server/hardware-and-software-requirements.md
Labels: Microsoft submitter

#783 Update migration-interop-guidance-for-teams-with-skype.md
  Teams/migration-interop-guidance-for-teams-with-skype.md
Labels: Microsoft Teams, Microsoft submitter

#785 updated line 345
  Teams/direct-routing-configure.md
Labels: Microsoft submitter

#798 added links
  Skype/SfbServer/deploy/deploy-clients/lrs-migration.md
Labels: Microsoft submitter

#792 Added link to training video
  Teams/get-clients.md
Labels: Microsoft submitter

#791 Added link to client training video
  Teams/msi-deployment.md
Labels: Microsoft submitter

#793 Added link to training video
  Teams/Office-365-groups.md
Labels: Microsoft submitter

#795 Added link to training
  Teams/Exchange-Teams-interact.md
Labels: Microsoft submitter

#794 Added link to training
  Teams/SharePoint-OneDrive-interact.md
Labels: Microsoft submitter

#802 Replaced two video links with aka links
  Teams/ITAdmin-readiness.md
Labels: Microsoft submitter

#764 remove double the
  Teams/manage-the-audio-conferencing-settings-for-a-user-in-teams.md
Labels: Microsoft Teams, Microsoft submitter

#804 Update feature-comparison.md
  Skype/SfBServer2019/plan/feature-comparison.md
Labels: Microsoft submitter

#806 Fixed typo
  Teams/Office-365-groups.md
Labels: Microsoft submitter

#807 Fixed type
  Teams/cloud-recording.md
Labels: Microsoft submitter

#765 Update manage-teams-skypeforbusiness-admin-center.md
  Teams/manage-teams-skypeforbusiness-admin-center.md
Labels: Microsoft Teams, Microsoft submitter

#778 Remove script reference
  Teams/quality-of-experience-review-guide.md
Labels: Microsoft Teams, Microsoft submitter

#810 fixed typo
  Skype/SfbOnline/audio-conferencing-in-office-365/manage-the-audio-conferencing-settings-for-my-organization.md
Labels: Microsoft submitter

#812 Fixed Typo
  Teams/cloud-recording.md
Labels: Microsoft submitter

#813 Fixed Typo
  Teams/log-files.md
Labels: Microsoft submitter

#781 Starting with CU7 SQL Server 2016 SP1 is supported as per KB4100776
  Skype/SfbServer/plan-your-deployment/requirements-for-your-environment/server-requirements.md
Labels: Microsoft submitter

#782 Made edits to clarify role and entry-points
  Teams/tenant-apps-catalog-teams.md
Labels: Microsoft submitter

#766 Update Known-issues.md
  Teams/Known-issues.md
Labels: Microsoft Teams

#819 added a link
  Skype/SfbServer/deploy/deploy-clients/lrs-migration.md
Labels: Microsoft submitter

#825 fixed link
  Teams/Known-issues.md
Labels: Microsoft submitter
