Repository MicrosoftDocs/OfficeDocs-SkypeForBusiness, pull requests merged in 2021-09, with the labels that each got.

#7771 Update teams-contact-center.md
  Teams/teams-contact-center.md
Labels: Microsoft submitter

#7776 Added a few seconds silence issue to known issue table
  Teams/direct-routing-media-optimization.md
Labels: Microsoft submitter

#7780 Update plan-for-teams-live-events.md
  Teams/teams-live-events/plan-for-teams-live-events.md
Labels: Microsoft submitter

#7787 Major missing dimensions update
  Teams/dimensions-and-measures-available-in-call-quality-dashboard.md
Labels: Microsoft submitter

#7789 Update tmr-meeting-recording-change.md
  Teams/tmr-meeting-recording-change.md
Labels: Microsoft submitter

#7811 Update teams-recording-policy.md
  Teams/teams-recording-policy.md
Labels: Microsoft submitter

#7815 Updated data for Audicodes
  Teams/direct-routing-border-controllers.md
Labels: Microsoft submitter

#7830 Update sfb-server-updates.md
  Skype/SfbServer/sfb-server-updates.md
Labels: Microsoft submitter

#7797 Update cloud-recording.md
  Teams/cloud-recording.md
Labels: Microsoft submitter

#7806 Update approval-admin.md
  Teams/approval-admin.md
Labels: Microsoft submitter, doc-enhancement

#7801 Fix date
  Teams/tmr-meeting-recording-change.md
Labels: doc-bug

#7493 Add recommendation for 32/64-bit version
  Teams/get-clients.md
Labels: Microsoft submitter

#7856 Updated Cisco firmware versions
  Teams/direct-routing-border-controllers.md
Labels: Microsoft submitter

#7876 Update toc.yml
  Teams/toc.yml
Labels: Microsoft submitter

#7883 Removed Notes for specific IP values, only ranges should be supported…
  Teams/direct-routing-plan.md
Labels: Microsoft submitter

#7868 Update teams-powershell-release-notes.md
  Teams/teams-powershell-release-notes.md
Labels: Microsoft submitter

#7891 Update teams-recording-policy.md
  Teams/teams-recording-policy.md
Labels: Microsoft submitter

#7909 Added EdgeMarc models to ATA devices
  Teams/direct-routing-border-controllers.md
Labels: Microsoft submitter

#7889 Update add-funds-and-manage-communications-credits.md
  Teams/add-funds-and-manage-communications-credits.md
Labels: Microsoft submitter

#7910 Update limits-specifications-teams.md
  Teams/limits-specifications-teams.md
Labels: Microsoft submitter

#7898 update GCCH DoD reset pin link
  Teams/reset-the-audio-conferencing-pin-in-teams.md
Labels: Microsoft submitter

#7925 Updated AC LMO firmware versions
  Teams/direct-routing-border-controllers.md
Labels: Microsoft submitter
