Repository MicrosoftDocs/OfficeDocs-SkypeForBusiness, pull requests merged in 2023-11, with the labels that each got.

#9666 Update view-only-meeting-experience.md
  Teams/view-only-meeting-experience.md
Labels: Microsoft submitter

#10558 Update direct-routing-voice-routing.md
  Teams/direct-routing-voice-routing.md
Labels: Microsoft submitter

#10572 Updated AC related SBC firmware version
  Teams/direct-routing-border-controllers.md
Labels: Microsoft submitter

#10578 Update new-teams-known-issues.md
  Teams/new-teams-known-issues.md
Labels: msteams/svc

#10591 add copilot option
  Teams/settings-policies-reference.md
Labels: msteams/svc, Tier1

#10582 add External meeting chat
  Teams/settings-policies-reference.md
Labels: msteams/svc, Tier1

#10592 Update new-teams-known-issues.md
  Teams/new-teams-known-issues.md
Labels: msteams/svc

#10593 Update new-teams-known-issues.md
  Teams/new-teams-known-issues.md
Labels: msteams/svc

#10594 Update direct-routing-media-optimization.md
  Teams/direct-routing-media-optimization.md
Labels: Microsoft submitter, msteams/svc, Tier1

#10588 Update support
  Teams/end-to-end-encrypted-meetings.md
Labels: msteams/svc, Tier1

#10619 Update direct-routing-plan.md
  Teams/direct-routing-plan.md
Labels: Microsoft submitter, msteams/svc, Tier1
