Repository MicrosoftDocs/OfficeDocs-SkypeForBusiness, pull requests merged in 2023-12, with the labels that each got.

#10645 Update direct-routing-media-optimization.md
  Teams/direct-routing-media-optimization.md
Labels: Microsoft submitter, msteams/svc, Tier1

#10648 add business
  Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md
Labels: msteams/svc, Tier1

#10639 Update new-teams-known-issues.md
  Teams/new-teams-known-issues.md
Labels: msteams/svc

#10661 Update security-remove-external-chat.md
  Teams/security-remove-external-chat.md
Labels: Microsoft submitter, msteams/svc

#10630 Update xml-config-file.md
  Teams/rooms/xml-config-file.md
Labels: Microsoft submitter, msteams/svc, itpro-rooms/subsvc, Tier2

#10428 Update microsoft-teams-rooms-configure-servicenow.md
  Teams/rooms/microsoft-teams-rooms-configure-servicenow.md
Labels: Microsoft submitter

#10666 Update security-remove-external-chat.md
  Teams/security-remove-external-chat.md
Labels: Microsoft submitter, msteams/svc

#10670 Update security-remove-external-chat.md
  Teams/security-remove-external-chat.md
Labels: Microsoft submitter, msteams/svc

#10654 Update teams-reporting-reference.md
  Teams/teams-analytics-and-reports/teams-reporting-reference.md
Labels: Microsoft submitter, msteams/svc

#10675 Update new-teams-known-issues.md
  Teams/new-teams-known-issues.md
Labels: msteams/svc

#10676 Update teams-contact-center.md
  Teams/teams-contact-center.md
Labels: Microsoft submitter, msteams/svc, Tier1

#10677 Update new-teams-known-issues.md
  Teams/new-teams-known-issues.md
Labels: msteams/svc
