Repository MicrosoftDocs/OfficeDocs-SkypeForBusiness, pull requests merged in 2024-01, with the labels that each got.

#10679 Update new-teams-known-issues.md
  Teams/new-teams-known-issues.md
Labels: msteams/svc

#10680 Update new-teams-known-issues.md
  Teams/new-teams-known-issues.md
Labels: msteams/svc

#10681 Update new-teams-known-issues.md
  Teams/new-teams-known-issues.md
Labels: msteams/svc

#10683 Update overview-meetings-webinars-town-halls.md
  Teams/overview-meetings-webinars-town-halls.md
Labels: Microsoft submitter, msteams/svc, meetings/subsvc

#10682 Update limits-specifications-teams.md
  Teams/limits-specifications-teams.md
Labels: Microsoft submitter, msteams/svc

#10685 Update new-teams-known-issues.md
  Teams/new-teams-known-issues.md
Labels: Microsoft submitter, msteams/svc

#10674 Update approval-admin.md
  Teams/approval-admin.md
Labels: Microsoft submitter, msteams/svc

#10692 Update new-teams-known-issues.md
  Teams/new-teams-known-issues.md
Labels: msteams/svc

#10690 PSTN usage Report- DR Available in GCC and GCCh/DOD
  Teams/teams-analytics-and-reports/teams-reporting-reference.md
Labels: Microsoft submitter, msteams/svc

#10691 add data baking line
  Teams/advanced-collaboration-analytics.md
Labels: Microsoft submitter, msteams/svc

#10694 Update new-teams-known-issues.md
  Teams/new-teams-known-issues.md
Labels: msteams/svc

#10696 Updated Italtel info
  Teams/direct-routing-border-controllers.md
Labels: Microsoft submitter, msteams/svc, Tier1

#10697 Update new-teams-known-issues.md
  Teams/new-teams-known-issues.md
Labels: msteams/svc

#10701 Updated Nokia data
  Teams/direct-routing-border-controllers.md
Labels: Microsoft submitter, msteams/svc, Tier1

#10700 change words about receiveSurveysMode
  Teams/manage-feedback-policies-in-teams.md
Labels: Microsoft submitter, msteams/svc

#10703 GCCH and DoD SIP certificate to MSPKI Certificate Authority change
  Teams/direct-routing-whats-new.md
Labels: Microsoft submitter, msteams/svc, Tier1

#10705 Update new-teams-known-issues.md
  Teams/new-teams-known-issues.md
Labels: msteams/svc

#10707 Added Enghouse SBC to LMO section
  Teams/direct-routing-border-controllers.md
Labels: Microsoft submitter, msteams/svc, Tier1
