Repository MicrosoftDocs/OfficeDocs-SkypeForBusiness, pull requests merged in 2024-11, with the labels that each got.

#10886 Add description about recording permission limitation
  Teams/tmr-meeting-recording-change.md
Labels: msteams/svc

#10887 Added Telnyx to certified vendors list
  Teams/direct-routing-border-controllers.md
Labels: Microsoft submitter, msteams/svc, Tier1

#10890 Added Vodia as SBC vendor and updated Telnyx information.
  Teams/direct-routing-border-controllers.md
Labels: Microsoft submitter, msteams/svc, Tier1

#10891 Add information indicating that auto-expiration is supported for transcriptions.
  Teams/meeting-recording.md
Labels: msteams/svc, Tier1
