Repository MicrosoftDocs/OfficeDocs-SkypeForBusiness, pull requests merged in 2024-08, with the labels that each got.

#10852 Update assign-policies-users-and-groups.md
  Teams/assign-policies-users-and-groups.md
Labels: Microsoft submitter, msteams/svc

#10850 Update direct-routing-protocols.md
  Teams/direct-routing-protocols.md
Labels: Microsoft submitter, msteams/svc, Tier1

#10851 Update direct-routing-plan.md
  Teams/direct-routing-plan.md
Labels: Microsoft submitter, msteams/svc, Tier1

#10853 Update manage-reactions-meetings.md
  Teams/manage-reactions-meetings.md
Labels: Microsoft submitter, msteams/svc, Tier2

#10854 Update teams-town-hall-usage-report.md
  Teams/teams-analytics-and-reports/teams-town-hall-usage-report.md
Labels: Microsoft submitter, msteams/svc
