Repository MicrosoftDocs/OfficeDocs-SkypeForBusiness, pull requests merged in 2024-03, with the labels that each got.

#10720 Add federation limitation
  Teams/teams-analytics-and-reports/external-domain-activity-report.md
Labels: Microsoft submitter, msteams/svc

#10728 Update view-only-meeting-experience.md
  Teams/view-only-meeting-experience.md
Labels: Microsoft submitter, msteams/svc

#10735 Update location-based-routing-plan.md
  Teams/location-based-routing-plan.md
Labels: Microsoft submitter, msteams/svc, Tier1

#10731 Update public-preview-doc-updates.md
  Teams/public-preview-doc-updates.md
Labels: msteams/svc

#10739 Update ITAdmin-readiness.md
  Teams/ITAdmin-readiness.md
Labels: Microsoft submitter, msteams/svc

#10741 Updated text to reflect newly added functionality
  Teams/direct-routing-survivable-branch-appliance.md
Labels: Microsoft submitter, msteams/svc, Tier1

#10736 Update pstn-usage-report.md
  Teams/teams-analytics-and-reports/pstn-usage-report.md
Labels: Microsoft submitter, msteams/svc, Tier1

#10742 Update pstn-usage-report.md retention table (removing DE, correcting UK --> GB)
  Teams/teams-analytics-and-reports/pstn-usage-report.md
Labels: Microsoft submitter, msteams/svc, Tier1

#10745 Update external-domain-activity-report.md
  Teams/teams-analytics-and-reports/external-domain-activity-report.md
Labels: Microsoft submitter, msteams/svc
