Repository MicrosoftDocs/OfficeDocs-SkypeForBusiness, pull requests merged in 2024-07, with the labels that each got.

#10815 Update licensing-enhance-teams.md
  Teams/teams-add-on-licensing/licensing-enhance-teams.md
Labels: Microsoft submitter, msteams/svc, Tier1, teams-premium/subsvc

#10820 Update limits-specifications-teams.md
  Teams/limits-specifications-teams.md
Labels: Microsoft submitter, msteams/svc

#10818 Update here-s-what-you-get-with-phone-system: removed duplicate paragraph about licensing
  Teams/here-s-what-you-get-with-phone-system.md
Labels: msteams/svc, Tier1

#10821 Update teams-classic-client-uninstall.md
  Teams/teams-classic-client-uninstall.md
Labels: Microsoft submitter, msteams/svc

#10823 Update manage-qna-for-teams.md
  Teams/manage-qna-for-teams.md
Labels: Microsoft submitter, msteams/svc, Tier2

#10830 Update overview-meetings-webinars-town-halls.md
  Teams/overview-meetings-webinars-town-halls.md
Labels: msteams/svc, meetings/subsvc

#10829 Update teams-reporting-reference.md
  Teams/teams-analytics-and-reports/teams-reporting-reference.md
Labels: msteams/svc

#10831 Update plan-town-halls.md
  Teams/plan-town-halls.md
Labels: msteams/svc, meetings/subsvc

#10833 Updated EOA for macOS
  Teams/teams-classic-client-end-of-availability.md
Labels: msteams/svc

#10839 Izzy edits
  Teams/teams-analytics-and-reports/external-domain-activity-report.md
Labels: msteams/svc

#10840 Revert "Izzy edits"
  Teams/teams-analytics-and-reports/external-domain-activity-report.md
Labels: Microsoft submitter, msteams/svc
