Repository MicrosoftDocs/OfficeDocs-SkypeForBusiness, pull requests merged in 2024-09, with the labels that each got.

#10858 Update export-teams-content.md
  Teams/export-teams-content.md
Labels: msteams/svc

#10864 Update licensing-enhance-teams.md
  Teams/teams-add-on-licensing/licensing-enhance-teams.md
Labels: Microsoft submitter, msteams/svc, Tier1, teams-premium/subsvc

#10863 Update configure-call-spam-filtering.md
  Teams/configure-call-spam-filtering.md
Labels: Microsoft submitter, msteams/svc, Tier1

#10865 Remove beta for edit history in export-teams-content.md
  Teams/export-teams-content.md
Labels: msteams/svc

#10866 Switched order of PowerShell instructions
  Teams/assign-change-or-remove-a-phone-number-for-a-user.md
Labels: Microsoft submitter, msteams/svc, Tier1
