Repository MicrosoftDocs/OfficeDocs-SkypeForBusiness, pull requests merged in 2024-05, with the labels that each got.

#10776 Update meeting-transcription-captions.md
  Teams/meeting-transcription-captions.md
Labels: msteams/svc, Tier1

#10775 [Teams Export API] calling out that export API response is not guaranteed to be in order of datetime
  Teams/export-teams-content.md
Labels: msteams/svc

#10783 Update calling-plans-for-office-365.md
  Teams/calling-plans-for-office-365.md
Labels: Microsoft submitter, msteams/svc, Tier1

#10784 [Teams Export API] Mention new capability in beta and its prerequisite
  Teams/export-teams-content.md
Labels: msteams/svc

#10785 Update tmr-meeting-recording-change.md
  Teams/tmr-meeting-recording-change.md
Labels: msteams/svc

#10782 Update block-inbound-calls.md
  Teams/block-inbound-calls.md
Labels: msteams/svc, Tier1

#10779 Update public-preview-doc-updates.md
  Teams/public-preview-doc-updates.md
Labels: Microsoft submitter, msteams/svc

#10781 Update new-teams-education.md
  Teams/new-teams-education.md
Labels: Microsoft submitter, msteams/svc

#10789 Update dial-voice-reference.md
  Teams/dial-voice-reference.md
Labels: Microsoft submitter, msteams/svc, Tier1

#10793 Update shared-line-appearance.md
  Teams/shared-line-appearance.md
Labels: Microsoft submitter, msteams/svc, Tier1

#10788 Add MFA information to CCM admin overview
  Teams/cross-cloud-meetings.md
Labels: Microsoft submitter, msteams/svc
