Repository MicrosoftDocs/OfficeDocs-SkypeForBusiness, pull requests merged in 2024-04, with the labels that each got.

#10748 Update ITAdmin-readiness.md
  Teams/ITAdmin-readiness.md
Labels: Microsoft submitter, msteams/svc

#10750 Update use-teams-panels.md (Typo "Teams Room"→"Teams Rooms")
  Teams/devices/use-teams-panels.md
Labels: msteams/svc, Tier1, itpro-devices/subsvc

#10717 Update xml-config-file.md
  Teams/rooms/xml-config-file.md
Labels: msteams/svc, itpro-rooms/subsvc, Tier2

#10668 Update common-area-mobile-phones.md
  Teams/devices/common-area-mobile-phones.md
Labels: msteams/svc, Tier1, itpro-devices/subsvc

#10751 Update inbound-call-routing.md
  Teams/inbound-call-routing.md
Labels: Microsoft submitter, msteams/svc, Tier1

#10753 Update new-teams-known-issues.md
  Teams/new-teams-known-issues.md
Labels: Microsoft submitter, msteams/svc

#10755 Added info to known issue section on CAE tokens
  Teams/direct-routing-survivable-branch-appliance.md
Labels: Microsoft submitter, msteams/svc, Tier1

#10756 Update info on the Media bit rate policy in meeting-policies-audio-and-video.md
  Teams/meeting-policies-audio-and-video.md
Labels: msteams/svc

#10758 Corrected streaming-ecdn-enterprise-content-delivery-network.md
  Teams/streaming-ecdn-enterprise-content-delivery-network.md
Labels: Microsoft submitter, msteams/svc

#10765 Fixes for text and images - New Teams on Mac
  Teams/media/new-teams-mac-notifications-monterey.png
  Teams/media/new-teams-mac-notifications.png
  Teams/media/new-teams-mac-screen-recording.png
  Teams/media/new-teams-mac-security.png
  Teams/media/new-teams-mac-switch-using-launchpad.png
  Teams/new-teams-mac-install-prerequisites.md
Labels: Microsoft submitter, msteams/svc

#10769 Updated Atos-Mitel SBC info
  Teams/direct-routing-border-controllers.md
Labels: Microsoft submitter, msteams/svc, Tier1

#10729 Update CQD-Power-BI-query-templates.md
  Teams/CQD-Power-BI-query-templates.md
Labels: msteams/svc, Tier1
