Repository MicrosoftDocs/OfficeDocs-SkypeForBusiness, pull requests merged in 2025-04, with the labels that each got.

#10965 Updated Audiocodes FW version
  Teams/direct-routing-border-controllers.md
Labels: Microsoft submitter, msteams/svc, Tier1

#10951 Update manage-voicemail-settings.md
  Teams/manage-voicemail-settings.md
Labels: msteams/svc, Tier1

#10968 Update direct-routing-protocols-sip.md
  Teams/direct-routing-protocols-sip.md
Labels: Microsoft submitter, msteams/svc, Tier1

#10969 Added Brekeke PBX info
  Teams/direct-routing-border-controllers.md
Labels: Microsoft submitter, msteams/svc, Tier1

#10940 Updated E911 and ELIN capabilities for Avaya
  Teams/direct-routing-border-controllers.md
Labels: Microsoft submitter, msteams/svc, Tier1

#10971 Update pstn-usage-report.md
  Teams/teams-analytics-and-reports/pstn-usage-report.md
Labels: Microsoft submitter, msteams/svc, Tier1

#10973 Added Nextgen SBC to the certified list.
  Teams/direct-routing-border-controllers.md
Labels: Microsoft submitter, msteams/svc, Tier1

#10974 Update pstn-usage-report.md
  Teams/teams-analytics-and-reports/pstn-usage-report.md
Labels: Microsoft submitter, msteams/svc, Tier1

#10895 Update search-private-teams.md
  Teams/search-private-teams.md
Labels: msteams/svc

#10976 Update set-up-live-chat.md
  Teams/set-up-live-chat.md
Labels: msteams/svc
