Repository MicrosoftDocs/OfficeDocs-SkypeForBusiness, pull requests merged in 2025-01, with the labels that each got.

#10905 Update meeting-policies-overview.md
  Teams/meeting-policies-overview.md
Labels: Microsoft submitter, msteams/svc

#10904 Teams media logs for VDI 1.0
  Teams/log-files.md
Labels: Microsoft submitter, msteams/svc

#10899 Update teams-recording-policy.md
  Teams/teams-recording-policy.md
Labels: msteams/svc, Tier3

#10909 Update create-an-org-wide-team.md
  Teams/create-an-org-wide-team.md
Labels: msteams/svc

#10922 Update meeting-transcription-captions.md to include missing language
  Teams/meeting-transcription-captions.md
Labels: msteams/svc, Tier1

#10925 Update block-incoming-chats.md
  Teams/block-incoming-chats.md
Labels: msteams/svc
