Repository MicrosoftDocs/OfficeDocs-SkypeForBusiness, pull requests merged in 2025-06, with the labels that each got.

#10994 Update bilateral-chat-enforcement.md
  Teams/bilateral-chat-enforcement.md
Labels: msteams/svc

#11000 Updated SBC vendors data
  Teams/direct-routing-border-controllers.md
Labels: Microsoft submitter, msteams/svc, Tier1, teams-calling/subsvc

#11002 Update setup-calendar-syncing-with-google-workspace.md
  Teams/setup-calendar-syncing-with-google-workspace.md
Labels: Microsoft submitter, msteams/svc
