Repository MicrosoftDocs/OfficeDocs-SkypeForBusiness, pull requests merged in 2025-03, with the labels that each got.

#10945 Update sms-overview.md
  Teams/sms-overview.md
Labels: msteams/svc, Tier1

#10946 Update audio-conferencing-with-direct-routing-for-gcch-and-dod.md
  Teams/audio-conferencing-with-direct-routing-for-gcch-and-dod.md
Labels: Microsoft submitter, msteams/svc, Tier1

#10902 Removing ACG from the list as it is not supported anymore.
  Teams/direct-routing-border-controllers.md
Labels: Microsoft submitter, msteams/svc, Tier1

#10949 Update audio-conferencing-with-direct-routing-for-gcch-and-dod.md
  Teams/audio-conferencing-with-direct-routing-for-gcch-and-dod.md
Labels: Microsoft submitter, msteams/svc, Tier1

#10950 Update set-up-live-chat.md
  Teams/set-up-live-chat.md
Labels: msteams/svc

#10944 Added Designer Message Policies messaging-policies-in-teams.md
  Teams/messaging-policies-in-teams.md
Labels: msteams/svc

#10955 Updated Avaya for E911 and Elin support
  Teams/direct-routing-border-controllers.md
Labels: Microsoft submitter, msteams/svc, Tier1

#10953 Update vdi-2.md
  Teams/vdi-2.md
Labels: Microsoft submitter, msteams/svc

#10956 Update log-files.md
  Teams/log-files.md
Labels: Microsoft submitter, msteams/svc

#10939 Update manage-queues-app.md
  Teams/manage-queues-app.md
Labels: Microsoft submitter, msteams/svc, Tier1

#10959 Updat Recordings and transcriptions automatically
  Teams/meeting-recording.md
Labels: msteams/svc, Tier1

#10963 Update view-only-meeting-experience.md
  Teams/view-only-meeting-experience.md
Labels: Microsoft submitter, msteams/svc
