Repository MicrosoftDocs/OfficeDocs-SkypeForBusiness, pull requests merged in 2025-02, with the labels that each got.

#10929 Update doc about MTR
  Teams/tmr-meeting-recording-change.md
Labels: msteams/svc

#10919 Updated Nokia firmware version
  Teams/direct-routing-border-controllers.md
Labels: Microsoft submitter, msteams/svc, Tier1

#10930 Update anonymous-users-in-meetings.md
  Teams/anonymous-users-in-meetings.md
Labels: msteams/svc, Tier1

#10931 Update operator-connect-conferencing-configure.md
  Teams/operator-connect-conferencing-configure.md
Labels: msteams/svc, Tier1, teams-audio-conferencing/subsvc

#10937 Update private-line.md
  Teams/private-line.md
Labels: msteams/svc, Tier1

#10938 Update media types to include a/v stream
  Teams/dimensions-and-measures-available-in-call-quality-dashboard.md
Labels: Microsoft submitter, msteams/svc, Tier1
